version: '2'

services:

  elasticsearch:
    image: zammad/zammad-docker-compose:elasticsearch
    restart: always

  nginx:
    depends_on:
      - zammad
    image: zammad/zammad-docker-compose:nginx
    links:
      - zammad-railsserver
      - zammad-websocket
    ports:
      - "80:80"
    restart: always
    volumes:
      - data-zammad:/home/zammad

  postgresql:
    image: zammad/zammad-docker-compose:postgresql
    restart: always

  zammad:
    image: zammad/zammad-docker-compose:zammad
    labels:
      - io.rancher.container.start_once=true
    restart: on-failure
    volumes:
      - data-zammad:/home/zammad

  zammad-railsserver:
    image: zammad/zammad-docker-compose:zammad-railsserver
    links:
      - elasticsearch
      - postgresql
      - zammad
    depends_on:
      - elasticsearch
      - postgresql
      - zammad
    restart: always

  zammad-scheduler:
    image: zammad/zammad-docker-compose:zammad-scheduler
    links:
      - elasticsearch
      - postgresql
      - zammad
    depends_on:
      - elasticsearch
      - postgresql
      - zammad
    restart: always

  zammad-websocket:
    image: zammad/zammad-docker-compose:zammad-websocket
    links:
      - postgresql
      - zammad
    depends_on:
      - postgresql
      - zammad
    restart: always

volumes:
  data-zammad:
    driver: local
