version: '2'

services:

  elasticsearch:
    build:
      context: .
      dockerfile: containers/elasticsearch/Dockerfile
    restart: always

  nginx:
    build:
      context: .
      dockerfile: containers/nginx/Dockerfile
    depends_on:
      - zammad
    links:
      - zammad-railsserver
      - zammad-websocket
    ports:
      - "80:80"
    restart: always
    volumes_from:
      - zammad

  postgresql:
    build:
      context: .
      dockerfile: containers/postgresql/Dockerfile
    restart: always

  zammad:
    build:
      context: .
      dockerfile: containers/zammad/Dockerfile
    depends_on:
      - elasticsearch
      - postgresql
    links:
      - elasticsearch
      - postgresql
    restart: always
    volumes:
      - data-zammad:/home/zammad

  zammad-railsserver:
    build:
      context: .
      dockerfile: containers/zammad-railsserver/Dockerfile
    depends_on:
      - elasticsearch
      - postgresql
      - zammad
    entrypoint: containers/zammad-railsserver/docker-entrypoint.sh
    links:
      - elasticsearch
      - postgresql
      - zammad
    restart: always
    volumes_from:
      - zammad

  zammad-scheduler:
    build:
      context: .
      dockerfile: containers/zammad-scheduler/Dockerfile
    depends_on:
      - elasticsearch
      - postgresql
      - zammad
    entrypoint: containers/zammad-scheduler/docker-entrypoint.sh
    links:
      - elasticsearch
      - postgresql
      - zammad
    restart: always
    volumes_from:
      - zammad

  zammad-websocket:
    build:
      context: .
      dockerfile: containers/zammad-websocket/Dockerfile
    depends_on:
      - postgresql
      - zammad
    entrypoint: containers/zammad-websocket/docker-entrypoint.sh
    links:
      - postgresql
      - zammad
    restart: always
    volumes_from:
      - zammad

volumes:
  data-zammad:
    driver: local
